# Generated by Django 4.2.7 on 2023-11-27 11:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['done', '-datetime']},
        ),
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 12, 4, 11, 18, 21, 326133, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
